thresholds:
  default:
    SQUARE0.6:
      ew_thresholds:
      - .inf
      - 0.450465146949864
      - 0.3596641894197092
      - 0.1673050633369712
      snr_edges:
      - 0
      - 30
      - 60
      - 90
      - inf
    SQUARE2.0:
      ew_thresholds:
      - .inf
      - 0.25249072004226036
      - 0.25055049227376003
      - 0.26695458621543366
      snr_edges:
      - 0
      - 30
      - 60
      - 90
      - inf
  NGC4030:
    SQUARE0.6:
      ew_thresholds:
      - .inf
      - 0.450465146949864
      - 0.3596641894197092
      - 0.1673050633369712
      snr_edges:
      - 0
      - 30
      - 60
      - 90
      - inf
    SQUARE2.0:
      ew_thresholds:
      - .inf
      - 0.25249072004226036
      - 0.25055049227376003
      - 0.26695458621543366
      snr_edges:
      - 0
      - 30
      - 60
      - 90
      - inf
  NGC0289:
    SQUARE0.6:
      ew_thresholds:
      - .inf
      - .inf
      - 0.8500089221866802
      - 0.75021318171639
      snr_edges:
      - 0
      - 10
      - 20
      - 30
      - inf
    SQUARE2.0:
      ew_thresholds:
      - .inf
      - .inf
      - 0.35220649414404764
      - 0.25133234361419454
  NGC1097:
    SQUARE0.6:
      ew_thresholds:
      - .inf
      - .inf
      - 1.0503474303521216
      - 0.6516262585413644
      snr_edges:
      - 0
      - 10
      - 20
      - 40
      - inf
    SQUARE2.0:
      ew_thresholds:
      - .inf
      - 0.6506770084291931
      - 0.45234572839690373
      - 1.4556131943711081
      snr_edges:
      - 0
      - 20
      - 40
      - 60
      - inf
